"""AG - change phone from int to string

Revision ID: 22abbaaa29ae
Revises: 7e74ce3a8595
Create Date: 2016-04-21 01:59:16.242414

"""

# revision identifiers, used by Alembic.
revision = '22abbaaa29ae'
down_revision = '7e74ce3a8595'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
