"""AGtype - change result init to include userid

Revision ID: afe76fa8c00c
Revises: None
Create Date: 2016-04-20 18:38:11.041002

"""

# revision identifiers, used by Alembic.
revision = 'afe76fa8c00c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
