"""AGtype - change phone from int to string 

Revision ID: e9c2534d2a01
Revises: 22abbaaa29ae
Create Date: 2016-04-21 02:03:25.276630

"""

# revision identifiers, used by Alembic.
revision = 'e9c2534d2a01'
down_revision = '22abbaaa29ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    ### end Alembic commands ###
